### ISSUE TITLE
Which open source license this repository uses.

### ISSUE THREAD

**Issue by zhiyangyou** [GPSnoopy/TriStripper#1]
Hi, thanks for the algorithm, it helped me solve a problem.

I would like to know which open source license this repository uses.

**Comment by GPSnoopy** [comment]
Hi @zhiyangyou,

The current license is found at the top of the header file: https://github.com/GPSnoopy/TriStripper/blob/master/include/tri_stripper.h

Mind you, this was selected 20 years ago and never revisited. It's a BSD-like license, fairly permissive.

**Comment by zhiyangyou** [comment]
Ok, I found it. Thanks!
:)
